version: 3.7.0

services:
  api:
    build: ./api
    ports:
      - "8000:80"
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_API_URL=http://localhost:8000
    restart: always